name: C++ CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build C++ components
        run: |
          cd cpp-components
          make

      - name: Run C++ tests
        run: |
          cd cpp-components
          ./test_binary # Заміни test_binary на реальне ім'я тестового виконуваного файлу
