name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          cd go-server
          go build -o go-server-binary main.go
          cd ..
          tar -czf release-assets.tar.gz go-server-binary cpp-components/*.out python-scripts/

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          name: release-assets.tar.gz
          path: ./release-assets.tar.gz
          label: "Multi-Language-Database Release"
